# Generated by Django 4.2.24 on 2025-09-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="detail_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/detail/",
                verbose_name="Детальное изображение",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/preview/",
                verbose_name="Превью изображение",
            ),
        ),
    ]
