# Generated by Django 4.2.24 on 2025-09-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_product_detail_image_product_preview_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="preview_image",
        ),
        migrations.AlterField(
            model_name="product",
            name="detail_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Изображение товара",
            ),
        ),
    ]
